### ISSUE TITLE
며칠전부터 방송알림이 두개가 뜹니다.

### ISSUE THREAD

**Issue by WingZeroMaster** [junah201/chzzk-discord-bot#1]
안녕하세요
먼저 치직 봇을 개발해주셔셔 감사합니다.
며칠전부터 방송알림이 두개가 뜨고 있는데 확인 부탁드리겠습니다.
(라이브를 켜면 해당 라이브 알림이 중복으로 두개 올라옴)
확인 부탁드리겠습니다.
감사합니다.

**Comment by junah201** [comment]
기존 새로운 방송을 체크하던 live_check lambda는 3분 마다 작동되고 있었지만, 해당 lambda가 3분 이상 소요되게 되면서 동시에 여러 번 live check를 하여 생긴 문제로 lambda의 호출 간격을 조정하고, timeout 시간을 늘려 해결하였습니다.
